
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbecbqeqkcjdoeznnwhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZWNicWVxa2NqZG9lem5ud2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODAyNjksImV4cCI6MjA2MzI1NjI2OX0.wEt9bhjQ6X4CNH5YwUx9JRz2KjKTX6F-9fwxZPpkkjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
